version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      next:
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/*"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "composer"
    directory: "/app-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      laravel:
        patterns:
          - "laravel/*"
          - "illuminate/*"
          - "symfony/*"
        update-types:
          - "major"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
